### ISSUE TITLE
cooperative document ?

### ISSUE THREAD

**Issue by emile22** [rezaki-ali/IRTF_SUSTAIN_RG#1]
current proposal of the charter is not editable. Can we use a format that enable contributors to do pull requests ?

**Comment by rezaki-ali** [comment]
Thanks very much Emile! I have uploaded the MS Word version of the document as well. 
I assume this resolves the issue.
Best regards,
Ali

**Comment by hakiri** [comment]
It appears that AI/ML is not explicitly addressed in the document, despite the fact that future internet architectures are likely to incorporate these technologies as core elements. 
Given the expected increase in power demand driven by AI/ML applications within internet infrastructure, it might be beneficial for the research group to highlight this aspect as well.
